export const FETCH_PRODUCTS = 'CART-FETCH_PRODUCTS'
export const ADD_TO_CART = 'CART-ADD_TO_CART'
export const REMOVE_FROM_CART = 'CART-REMOVE_FROM_CART';

export const FILTER_PRODUCTS_BY_SIZE = 'CART-FILTER_PRODUCTS_BY_SIZE';
export const ORDER_PRODUCTS_BY_PRICE = 'CART-ORDER_PRODUCTS_BY_PRICE';